/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package priceDisplay;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getPriceLabel( int price , String name ) {
        String label = String.format("A %s is £%d", name, price);
        return label;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getPriceLabel(15, "plant"));
    }
}
